// <auto-generated />
namespace RestaurantManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Convertednumberofguesttostring : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Convertednumberofguesttostring));
        
        string IMigrationMetadata.Id
        {
            get { return "201612011941578_Converted number of guest to string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
